---
cluster_name: "k8s-prod"
kubernetes_version: "1.35"

pod_network_cidr: "192.168.0.0/16"
service_cidr: "10.96.0.0/12"
vcn_cidr: "10.0.0.0/16"

# Component versions
cilium_version: "1.19.1"
cilium_cli_version: "0.16.20"
cilium_chart_version: "1.19.1"
gateway_api_version: "1.2.1"
argocd_version: "2.13.2"
sealed_secrets_chart_version: "2.17.9"
sealed_secrets_app_version: "0.33.1"
cert_manager_version: "1.16.2"
metrics_server_version: "0.7.2"
prometheus_chart_version: "79.9.0"
loki_stack_chart_version: "2.10.3"
longhorn_version: "1.7.2"
longhorn_chart_version: "1.7.2"

# Cilium settings
cilium_enable_hubble: true

# Monitoring settings
prometheus_retention: "7d"
grafana_admin_password: "admin"

# Logging settings
loki_retention: "3d"

# ArgoCD settings
argocd_enable_notifications: false
